### ISSUE TITLE
NullPointerExceptin

### ISSUE THREAD

**Issue by ogulcan** [maurycyw/StaggeredGridView#12]
Hi,

Sometimes getting this error, not sure what causes. 

java.lang.NullPointerException
at android.os.Parcel.readIntArray(Parcel.java:678)
com.test.example..StaggeredGridView$SavedState.<init>(StaggeredGridView.java:2105)
com.test.example.viewpager.StaggeredGridView$SavedState.<init>(StaggeredGridView.java:2101)
at com.test.example.viewpager.StaggeredGridView$SavedState$1.createFromParcel(StaggeredGridView.java:2129)
at com.test.example.viewpager.StaggeredGridView$SavedState$1.createFromParcel(StaggeredGridView.java:1)
at android.os.Parcel.readParcelable(Parcel.java:1919)
at android.os.Parcel.readValue(Parcel.java:1784)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2050)
at android.os.Parcel.readSparseArray(Parcel.java:1506)
at android.os.Parcel.readValue(Parcel.java:1841)
at android.os.Parcel.readMapInternal(Parcel.java:2021)
at android.os.Bundle.unparcel(Bundle.java:208)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1167)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1463)
at android.app.Activity.onRestoreInstanceState(Activity.java:843)
at android.app.Activity.performRestoreInstanceState(Activity.java:815)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1096)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
at android.app.ActivityThread.access$2300(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

Btw, here is line 2105:

```
    private SavedState(Parcel in) {
        super(in);
        firstId = in.readLong();
        position = in.readInt();
        in.readIntArray(topOffsets);
        in.readTypedList(mapping, ColMap.CREATOR);  
    }
```

**Comment by BenMoment** [comment]
I see it often too...

**Comment by v3nko** [comment]
Fix:
Replace this constructors:

```
    private SavedState(Parcel in) {
        super(in);
        firstId = in.readLong();
        position = in.readInt();
        topOffsets = in.createIntArray();
        mapping = new ArrayList<ColMap>();
        in.readTypedList(mapping, ColMap.CREATOR);
    }
```

And

```
    private ColMap(Parcel in) {
        tempMap = in.createIntArray();
        values = new ArrayList<Integer>();
        for (int index = 0; index < tempMap.length; index++) {
            values.add(tempMap[index]);
        }
    }
```

**Comment by ghost** [comment]
@q1p Thank you! It works!

**Comment by zhmkof** [comment]
@q1p thank you

**Comment by xMikeTx** [comment]
@q1p +1 (happened when android tried to restore the activity)

**Comment by zhmkof** [comment]
It is not works completely. When resume the activity, it works.But if restore the activity, it is not working completely.
I use a FragmentActivvity to setup three StaggeredGridView, it happened when android tried to restore the FragmentActivity, debug info show that the second and third StaggeredGridView.SavedState.topOffsets and mapping is null when Parcelable.writeToParcel.
Is that anybody help?

**Comment by briangriffey** [comment]
@q1p can you package this into a pull request if you still see the problem?

**Comment by v3nko** [comment]
@briangriffey seems it's already fixed by several of commits.

**Comment by briangriffey** [comment]
Closing this issue then.

**Comment by doug-nara** [comment]
Was there a way to reproduce this error consistently?
